BEGIN;

CREATE TABLE IF NOT EXISTS sr.seasons (
  source_api text NOT NULL,
  season_id text NOT NULL,
  league_id text NOT NULL,
  league_name text,
  league_alias text,
  season_year integer NOT NULL,
  season_type text NOT NULL,
  season_name text,
  is_current boolean DEFAULT false,
  status text,
  start_date date,
  end_date date,
  PRIMARY KEY (source_api, season_id),
  UNIQUE (source_api, league_id, season_year, season_type)
);

CREATE TABLE IF NOT EXISTS sr.teams (
  source_api text NOT NULL,
  sr_team_id text NOT NULL,
  name text,
  alias text,
  market text,
  reference text,
  venue_id text,
  conference_id text,
  conference_name text,
  division_id text,
  division_name text,
  country text,
  country_code text,
  competition_id text,
  affiliated_sr_team_id text,
  owner text,
  founded integer,
  championships_won integer,
  playoff_appearances integer,
  team_colors_json jsonb,
  roster_json jsonb,
  depth_chart_json jsonb,
  PRIMARY KEY (source_api, sr_team_id)
);

CREATE TABLE IF NOT EXISTS sr.players (
  source_api text NOT NULL,
  sr_id text NOT NULL,
  reference text,
  full_name text,
  first_name text,
  last_name text,
  abbr_name text,
  status text,
  position text,
  primary_position text,
  jersey_number text,
  experience text,
  birthdate date,
  birth_place text,
  high_school text,
  college text,
  rookie_year integer,
  height integer,
  weight integer,
  sr_team_id text,
  draft_year integer,
  draft_round integer,
  draft_pick integer,
  sr_draft_team_id text,
  is_free_agent boolean DEFAULT false,
  updated_at timestamptz,
  references_json jsonb,
  seasons_json jsonb,
  PRIMARY KEY (source_api, sr_id)
);

CREATE TABLE IF NOT EXISTS sr.games (
  source_api text NOT NULL,
  game_id text NOT NULL,
  season_id text,
  status text,
  coverage text,
  scheduled_at timestamptz,
  lead_changes integer,
  times_tied integer,
  clock text,
  quarter integer,
  is_track_on_court boolean,
  entry_mode text,
  duration text,
  attendance integer,
  away_sr_team_id text,
  away_team_name text,
  away_team_alias text,
  away_pts integer,
  home_sr_team_id text,
  home_team_name text,
  home_team_alias text,
  home_pts integer,
  series_id text,
  series_game_number integer,
  tournament_id text,
  round_name text,
  bracket_name text,
  region_name text,
  home_seed integer,
  away_seed integer,
  neutral_site boolean DEFAULT false,
  reference text,
  venue_id text,
  venue_name text,
  venue_capacity integer,
  venue_address text,
  venue_city text,
  venue_state text,
  venue_zip text,
  venue_country text,
  venue_lat text,
  venue_lng text,
  venue_sr_id text,
  category_id text,
  category_name text,
  competition_id text,
  stage_type text,
  stage_phase text,
  group_id text,
  group_name text,
  cup_round_id text,
  cup_round_number integer,
  cup_round_total_games integer,
  title text,
  season_year integer,
  season_type text,
  broadcast_json jsonb,
  time_zones_json jsonb,
  summary_json jsonb,
  PRIMARY KEY (source_api, game_id)
);

CREATE TABLE IF NOT EXISTS sr.game_team_stats (
  source_api text NOT NULL,
  game_id text NOT NULL,
  sr_team_id text NOT NULL,
  opposite_sr_team_id text,
  is_home boolean,
  pts integer,
  minutes text,
  fgm integer,
  fga integer,
  fg_pct numeric(5,2),
  fg3m integer,
  fg3a integer,
  fg3_pct numeric(5,2),
  fg2m integer,
  fg2a integer,
  fg2_pct numeric(5,2),
  ftm integer,
  fta integer,
  ft_pct numeric(5,2),
  oreb integer,
  dreb integer,
  reb integer,
  ast integer,
  stl integer,
  blk integer,
  tov integer,
  pf integer,
  tech_fouls integer,
  flagrant_fouls integer,
  pts_in_paint integer,
  fast_break_pts integer,
  second_chance_pts integer,
  pts_off_turnovers integer,
  biggest_lead integer,
  ts_att numeric(7,2),
  ts_pct numeric(5,2),
  efg_pct numeric(5,2),
  bench_pts integer,
  PRIMARY KEY (source_api, game_id, sr_team_id)
);

CREATE TABLE IF NOT EXISTS sr.game_player_stats (
  source_api text NOT NULL,
  game_id text NOT NULL,
  sr_id text NOT NULL,
  sr_team_id text,
  is_played boolean DEFAULT true,
  is_starter boolean DEFAULT false,
  minutes text,
  seconds_played integer,
  pts integer,
  fgm integer,
  fga integer,
  fg_pct numeric(5,2),
  fg3m integer,
  fg3a integer,
  fg3_pct numeric(5,2),
  fg2m integer,
  fg2a integer,
  fg2_pct numeric(5,2),
  ftm integer,
  fta integer,
  ft_pct numeric(5,2),
  oreb integer,
  dreb integer,
  reb integer,
  ast integer,
  stl integer,
  blk integer,
  tov integer,
  pf integer,
  tech_fouls integer,
  flagrant_fouls integer,
  plus_minus integer,
  efficiency integer,
  efficiency_game_score numeric(5,2),
  double_double boolean,
  triple_double boolean,
  pts_in_paint integer,
  second_chance_pts integer,
  pts_off_turnovers integer,
  ast_tov_ratio numeric(5,2),
  fouls_drawn integer,
  blocked_att integer,
  ts_att numeric(7,2),
  ts_pct numeric(5,2),
  efg_pct numeric(5,2),
  PRIMARY KEY (source_api, game_id, sr_id)
);

CREATE TABLE IF NOT EXISTS sr.game_period_scores (
  source_api text NOT NULL,
  game_id text NOT NULL,
  sr_team_id text NOT NULL,
  period_number integer NOT NULL,
  period_type text NOT NULL,
  sequence integer,
  pts integer,
  PRIMARY KEY (source_api, game_id, sr_team_id, period_number, period_type)
);

CREATE TABLE IF NOT EXISTS sr.pbp (
  source_api text NOT NULL,
  game_id text NOT NULL,
  status text,
  period integer,
  clock text,
  away_pts integer,
  home_pts integer,
  pbp_json jsonb,
  PRIMARY KEY (source_api, game_id)
);

CREATE INDEX IF NOT EXISTS games_source_scheduled_at_idx ON sr.games (source_api, scheduled_at);
CREATE INDEX IF NOT EXISTS games_source_season_id_idx ON sr.games (source_api, season_id);
CREATE INDEX IF NOT EXISTS games_source_home_team_idx ON sr.games (source_api, home_sr_team_id);
CREATE INDEX IF NOT EXISTS games_source_away_team_idx ON sr.games (source_api, away_sr_team_id);

CREATE INDEX IF NOT EXISTS players_source_reference_idx ON sr.players (source_api, reference);
CREATE INDEX IF NOT EXISTS players_source_team_idx ON sr.players (source_api, sr_team_id);

COMMIT;
